-- Phase 10: reproducible rate-limit foundation.
-- The live project already contains this structure; this migration makes the
-- repository's migration history self-contained and idempotent.

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  key text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_rate_limit_events_key_action_created
  on public.rate_limit_events(key, action, created_at desc);

alter table public.rate_limit_events enable row level security;

drop policy if exists "rate limit events no direct access" on public.rate_limit_events;
create policy "rate limit events no direct access"
  on public.rate_limit_events
  for all to authenticated
  using (false)
  with check (false);

grant execute on function public.check_rate_limit(text, text, integer, integer) to authenticated;
revoke execute on function public.check_rate_limit(text, text, integer, integer) from anon;
