-- Phase 10: reproducible rate-limit foundation.

create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  key text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_rate_limit_events_key_action_created
  on public.rate_limit_events(key, action, created_at desc);

alter table public.rate_limit_events enable row level security;

drop policy if exists "rate limit events no direct access" on public.rate_limit_events;
create policy "rate limit events no direct access"
  on public.rate_limit_events
  for all to authenticated
  using (false)
  with check (false);

create or replace function public.check_rate_limit(
  p_key text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if p_key is null or length(p_key) = 0
     or p_action is null or length(p_action) = 0
     or p_limit is null or p_limit < 1
     or p_window_seconds is null or p_window_seconds < 1 then
    return false;
  end if;

  delete from public.rate_limit_events
  where created_at < now() - interval '1 hour';

  select count(*) into v_count
  from public.rate_limit_events
  where key = p_key
    and action = p_action
    and created_at >= now() - make_interval(secs => p_window_seconds);

  if v_count >= p_limit then
    return false;
  end if;

  insert into public.rate_limit_events(key, action)
  values (p_key, p_action);

  return true;
end;
$$;

grant execute on function public.check_rate_limit(text, text, integer, integer) to authenticated;
revoke execute on function public.check_rate_limit(text, text, integer, integer) from anon;
